
<a class="btn btn-primary" href="<?=$this->url('InstructionForm/nuovo')?>" role="button">Nuova Istruzione</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Titolo</th>
            <th>Istruzione</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->lista as $instruction) { ?>
        <tr>
            <th scope="row"><?=$instruction->getNome()?></th>
            <td><?=$instruction->getTitolo()?></td>
            <td><?=$instructiont->getDescrizione()?></td>
        <!--    <td>
                <a class="btn btn-default" href="" role="button">modifica</a>
                <a class="btn btn-default" href="<?//=$this->url('zfcadmin/prodotti/elimina', ['codice' => $prodotto->getCodice()])?>" role="button">elimina</a>
            </td> -->
        </tr>
        <?php } ?>
    </tbody>
</table>
