<form class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-2 control-label">Titolo</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" placeholder="Titolo">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Nome</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" placeholder="Nome">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Istruzioni</label>
    <div class="col-sm-4">
      <textarea class="form-control" rows="3"></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Invia</button>
    </div>
  </div>
</form>
