<?php

namespace InstructionForm\Entity\Repository;

/**
 * ProdottiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstructionRepository extends \Doctrine\ORM\EntityRepository
{
}
