<div class="container-fluid">
  <div class="row banner-home">

    <div class="col-sm-offset-2 col-md-9">
      <h1>HowTos Form</h1>
    </div>
    <div class="col-sm-offset-2 col-sm-10">
    <!--  <button type="submit"  href="<?//=$this->url('')?>" class="btn btn-default">Entra</button> -->
      <a class="btn btn-primary" href="<?=$this->url('instructionform')?>" role="button">ENTRA</a>

    </div>
  </div>
</div>
